services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: R2wEG9
      POSTGRES_DB: EmployeeManagementDB
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d EmployeeManagementDB" ]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: EmployeeManagementServer/Dockerfile
    ports:
      - "5290:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      db:
        condition: service_started  # Запускается после старта db
    networks:
      - app-network

  client:
    build:
      context: .
      dockerfile: EmployeeManagementClient/Dockerfile
    ports:
      - "4200:80"
    depends_on:
      api:
        condition: service_started  # Запускается после успешного старта api
    networks:
      - app-network

  usermanagementapp:
    build:
      context: .
      dockerfile: UserManagementApp/Dockerfile
    depends_on:
      db:
        condition: service_started  # Запускается после старта db
    networks:
      - app-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
