# Stage 1: Build the Angular app
FROM node:18 AS build

WORKDIR /app

# Copy package.json and package-lock.json to install dependencies
COPY EmployeeManagementClient/package*.json ./

RUN npm install

# Copy the rest of the application files
COPY EmployeeManagementClient/. .

# Build the application
RUN npm run build --prod

# Stage 2: Serve the app with Nginx
FROM nginx:alpine

# Copy the nginx configuration file
COPY EmployeeManagementClient/nginx.conf /etc/nginx/conf.d/default.conf

# Copy the built app files from the previous stage
COPY --from=build /app/dist/employee-management-client /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
